int main(void);
void print_alphabet(void);
int _islower(int c);
int _putchar(char c);
int _isalpha(int c);
int print_sign(int n);
void print_to_98(int n);
int add(int a, int b);
void times_table(void);
void jack_bauer(void);
void print_alphabet_x10(void);
